language: objective-c
osx_image: xcode8.1
podfile: Example/Podfile
before_install:
    - gem install cocoapods
    - pod install --project-directory=Example
before_script:
    - export LANG=en_US.UTF-8
script: 
    - set -0 pipefail && xcodebuild test -workspace Example/Example.xcworkspace -scheme Example iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
    - pod lib lint
