language: objective-c
osx_image: xcode8.1
xcode_sdk: iphonesimulator10.1
# before_install:
#     - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
#     - pod install
before_script:
  - export LANG=en_US.UTF-8
# xcode_workspace: Example/Example.xcworkspace
xcode_project: NoticeBar.xcodeproj
xcode_scheme: NoticeBar
